version: '3.7'

services:
    wordpress:
        image: wordpress:latest
        links:
            - db:mysql
        networks:
            mynet:
        ports:
            - "8888:80"
        volumes:
            - wp-vol:/var/www/html
        depends_on:
            - db
    db:
        image: mariadb:latest
        env_file:
            - ./mysql.env
        networks:
            mynet:
                ipv4_address: 172.20.0.2
        volumes:
            - mysql-vol:/var/lib/mysql
        command:
            'mysqld --innodb-flush-method=fsync'

volumes:
    wp-vol:
        driver_opts:
            type: none
            device: /c/Users/doxas/tmp/wptest/html
            o: bind
    mysql-vol:
        driver_opts:
            type: none
            device: /c/Users/doxas/tmp/wptest/mysql
            o: bind

networks:
    mynet:
        driver: bridge
        ipam:
            driver: default
            config:
                - subnet: 172.20.0.0/24


